### PR TITLE
Remove the need for sudo on travis linux

### PR DESCRIPTION
**Pull request by stephengroat**
use travis apt addon to install packages

### CODE REVIEW

**Comment by kapoorlakshya** [comment]
Hi @stephengroat, this is cool! I'm new to Travis CI and just came across the [doc](https://docs.travis-ci.com/user/installing-dependencies/) for APT addon. Will definitely use this in the future 👍.

I'm okay with merging this, but will wait and see if @titusfortner has any feedback.

**Review by titusfortner — APPROVED** [review]
Looks good, thank for your submission.

**Comment by kapoorlakshya** [comment]
@stephengroat Can you please squash your commits and force-push? Will rebase and merge after.

**Comment by stephengroat** [comment]
@kapoorlakshya no worries, done.

can also be done through the web ui now! https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by kapoorlakshya** [comment]
Closes #46 as well.

**Comment by kapoorlakshya** [comment]
@stephengroat Sorry, I missed your comment before merging.

I did notice that, but when I did a "Squash and Merge" through the UI, it put 2 commits instead of 1 for some reason. I use Bitbucket at work and it only puts 1 commit, so I was confused if I did something incorrectly or if Github behaves differently. See my commits on Mar 19 here - https://github.com/titusfortner/webdrivers/commits/master

Squashing locally allowed me to "Rebase and Merge" and keep the log clean. Please let me know if I am misunderstanding how it works. Thanks!

**Comment by stephengroat** [comment]
@kapoorlakshya - sorry about that, i've used it in Github for awhile and it seems to only make 1 commit for me - see https://github.com/stephengroat/whitelist/commits/master and https://github.com/stephengroat/whitelist/pull/8

**Comment by kapoorlakshya** [comment]
That's good! I'll give it another try then.

**Pull request merged**
