### PR TITLE
Raise BrowserNotFound if Chrome and Edge binary are not found.

### LINKED ISSUE #144: `ArgumentError: wrong first argument` on `rails webdrivers:chromedriver:update`
#### Summary
[`rails webdrivers:chromedriver:update`](https://github.com/titusfortner/webdrivers#rake-tasks) results in error `ArgumentError: wrong first argument`.

#### Debug Info

`Using webdrivers 4.1.0`

```bash
$ RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

rails aborted!
ArgumentError: wrong first argument
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/system.rb:150:in `popen'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/system.rb:150:in `call'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/chrome_finder.rb:79:in `linux_version'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/chrome_finder.rb:10:in `version'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/chromedriver.rb:46:in `browser_version'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/chromedriver.rb:106:in `release_version'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/chromedriver.rb:32:in `latest_version'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/common.rb:133:in `correct_binary?'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/common.rb:89:in `update'
/builds/some/app/vendor/ruby/2.5.0/gems/webdrivers-4.1.0/lib/webdrivers/tasks/chromedriver.rake:23:in `block (3 levels) in <top (required)>'
/builds/some/app/vendor/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/builds/some/app/vendor/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/builds/some/app/vendor/ruby/2.5.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/builds/some/app/vendor/ruby/2.5.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => webdrivers:chromedriver:update
(See full trace by running task with --trace)

```

* Webdrivers version: [`4.1.0`](https://rubygems.org/gems/webdrivers/versions/4.1.0)
* Ruby version: [`2.5.0`](https://github.com/docker-library/ruby/blob/aacff4398185738d84232f1685df12306be13114/2.5/stretch/Dockerfile)
* Operating system / CI Environment: [Docker image `ruby:2.5`](https://github.com/docker-library/ruby/blob/aacff4398185738d84232f1685df12306be13114/2.5/stretch/Dockerfile) on [GitLab CI](https://about.gitlab.com/product/continuous-integration/).
* Browser and version: It should connect remotely to an instance of the  [`selenium/standalone-chrome:latest`](https://hub.docker.com/r/selenium/standalone-chrome/tags) Docker image.

#### Expected Behaviour
No exception should appear

#### Actual Behaviour
See above.

### PR DESCRIPTION
**Pull request by kapoorlakshya**
Also added specs for `EdgeFinder`.

Fixes #144.

### CODE REVIEW

**Comment by kapoorlakshya** [comment]
I have only tested this on Windows. Still need to test it with the rake tasks on Linux and macOS.

**Review by titusfortner — APPROVED** [review]
LGTM

**Comment by twalpole** [comment]
LGTM

**Review by twalpole — APPROVED** [review]

**Comment by kapoorlakshya** [comment]
Tested this on Linux and it works as expected. Merging!

**Pull request merged**
